<%--
    Document   : footer
    Created on : 13 Feb, 2014, 3:15:40 PM
    Author     : MurthyK
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link type="text/css" rel="stylesheet" href="/QuickKlix/CSS/loginRegistrationStyle.css" />
        <link rel="shortcut icon" href="/QuickKlix/images/BTabIcon/favicon.ico" type="image/x-icon" />
    </head>
    <body>
   <%--<div id="footerContainer" style="margin-left: 10px;width: 950px;height: 243px;"><br/>--%>
   <div id="footerContainer"><br/>
   <div style="text-align:left;margin-left:-45px;">
                <p style="margin-left: 0px;margin-top: 18px;text-align: left;font: bold 1em/1.25em sans-serif;width:960px;position:absolute;"><font style=" text-decoration: none;color: white;margin-left: 70px;position:absolute;">STATIC PAGES</font><font style=" text-decoration: none;color: white;margin-left: 262px;position:absolute;">SITE MAP</font>  <font style=" text-decoration: none;color: white;margin-left: 454px;position:absolute;">CONTACT US</font>   <font style=" text-decoration: none;color: white;margin-left: 646px;position:absolute;">LEGAL</font>   <font style=" text-decoration: none;color: white;margin-left: 840px;position:absolute;white-space: nowrap;">WHERE TO FIND US</font>   </p>

                <p style="margin-left: 0px;font-size:12px;margin-top: 55px;font: 1.1em/1.25em sans-serif;position:absolute;width:960px;"><a target="_blank" href="homePage.action" style=" text-decoration: none;color: white;margin-left: 70px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Home">Home</a><a href="userLandingHome.action" style=" text-decoration: none;color: white;margin-left: 262px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="User Home">User Home</a>    <a target="_blank" href="contactusPage.action" style=" text-decoration: none;color: white;margin-left: 454px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Send a Message">Send a Message</a> <a target="_blank" href="termsAndConditionsPopup.action" style=" text-decoration: none;color: white;margin-left: 646px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Terms and Conditions">Terms and Conditions</a>   <a target="_blank" href="https://www.facebook.com/quickklix" style=" text-decoration: none;color: white;margin-left: 840px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Facebook">Facebook</a>  </p>
                <p style="margin-left: 0px;font-size:12px;margin-top: 75px;font: 1.1em/1.25em sans-serif;position:absolute;width:960px;"><a target="_blank" href="aboutusPage.action" style=" text-decoration: none;color: white;margin-left: 70px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="About Us">About Us</a> <a href="campaignPlanRedirection.action" style=" text-decoration: none;color: white;margin-left: 262px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Campaign Plan">Campaign Plan</a> <font style=" text-decoration: none;color: white;margin-left: 454px;font-weight: normal;position:absolute;" title="Email">Email: <a target="_blank" href="contactusPage.action" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" style="font-weight: normal;color: white;"><u>info@quickklix.com</u></a></font> <a target="_blank" href="privacyPolicyPopup.action" style=" text-decoration: none;color: white;margin-left: 646px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Privacy Policy">Privacy Policy</a> <a target="_blank" href="https://www.twitter.com/quickklix" style=" text-decoration: none;color: white;margin-left: 840px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Twitter">Twitter</a>     </p>
                <p style="margin-left: 0px;font-size:12px;margin-top: 95px;font: 1.1em/1.25em sans-serif;position:absolute;width:960px;"><a target="_blank" href="productsPage.action" style=" text-decoration: none;color: white;margin-left: 70px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Products">Products</a><a href="targetMarketRedirection.action" style=" text-decoration: none;color: white;margin-left: 262px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Target Market">Target Market</a>   <a target="_blank" href="https://www.linkedin.com/quickklix" style=" text-decoration: none;color: white;margin-left: 840px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="LinkedIn">LinkedIn</a></p>
                <p style="margin-left: 0px;font-size:12px;margin-top: 115px;font: 1.1em/1.25em sans-serif;position:absolute;width:960px;"><a target="_blank" href="mediaoutletPage.action" style=" text-decoration: none;color: white;margin-left: 70px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Members">Members</a><a href="mediaPlanRedirection.action" style=" text-decoration: none;color: white;margin-left: 262px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Media Plan">Media Plan</a>   <a target="_blank" href="sendInvitation.action" style=" text-decoration: none;color: white;margin-left: 840px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Send Invitation">Send Invitation</a> </p>
                <p style="margin-left: 0px;font-size:12px;margin-top: 135px;font: 1.1em/1.25em sans-serif;position:absolute;width:960px;"><a target="_blank" href="contactusPage.action" style=" text-decoration: none;color: white;margin-left: 70px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Contact Us">Contact Us</a><a href="reportsRedirection.action" style=" text-decoration: none;color: white;margin-left: 262px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Reports">Reports</a> </p>
                <p style="margin-left: 0px;font-size:12px;margin-top: 155px;font: 1.1em/1.25em sans-serif;position:absolute;width:960px;"><a href="userLogout.action" style=" text-decoration: none;color: white;margin-left: 70px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Logout">Logout</a><a href="analyticsRedirection.action" style=" text-decoration: none;color: white;margin-left: 262px;font-weight: normal;position:absolute;" onMouseOver="this.style.color='#00a9f1';" onMouseOut="this.style.color='white';" title="Analytics">Analytics</a> </p>

    </div><br/>
    <p style="margin-top: 174px;margin-left: 198px;font: 1.1em/1.25em sans-serif;position:absolute;color: white;">Copyright © 2011 QuickKlix All Rights Reserved. Legal and Copyright Patent Pending</p><br/>
    <div class="clear"></div>
	</div>
    </body>
</html>
